# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 198f8bf17a67214feeae9517604dfb1cf94d00c6e2892ac4619670a1e9a60039b96089f2a8445c015b78dc9700b13ed1ea2ffbdc30e4211050be5955f32d61f3

test:
  secret_key_base: 73087d4867f60780966019f61cc94001c5b168af7c30a97d5d50c83c502d04440a803ba8c9c3adc3b3fddcd73e1a18b6138d4e12e45c16da7049ee067b414710

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
